import type { ModelData, OnboardingPhaseStep } from './types';

export const MODELS: ModelData[] = [
  {
    id: 'm1',
    name: 'Tyler Rex',
    niche: 'Gay Bear Fitness',
    handle: '@onlytylerrex',
    igHandle: '@tylerrex_fit',
    color: '#ff0069',
    initials: 'TR',
    status: 'Active',
    pipelineStep: 'Editing',
    reelsInPipeline: 3,
    mrr: 4200,
    subscribers: 1840,
    manager: 'Jordan M.',
    onboardingPhase: 7,
    contentReceived: 100,
    bio: 'Gay bear fitness creator focused on strength training, body positivity, and gym lifestyle content.',
    onboardingSteps: [
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Face references uploaded (5+)', done: true, phase: 4 },
      { label: 'Soul ID trained (Higgsfield)', done: true, phase: 4 },
      { label: 'First AI batch generated', done: true, phase: 4 },
      { label: 'Batch reviewed & approved', done: true, phase: 4 },
      { label: 'Vault loaded (10+ PPV pieces)', done: true, phase: 4 },
      { label: 'First 2 weeks scheduled', done: true, phase: 5 },
      { label: 'Welcome sequence set up', done: true, phase: 5 },
      { label: 'Chatter briefed', done: true, phase: 5 },
      { label: 'Account launched', done: true, phase: 6 },
      { label: 'First PPV blast sent', done: true, phase: 6 },
      { label: 'Traffic campaigns running', done: true, phase: 6 },
      { label: 'Week 1 performance reviewed', done: true, phase: 7 },
      { label: 'Strategy call complete', done: false, phase: 7 },
    ] as OnboardingPhaseStep[],
  },
  {
    id: 'm2',
    name: 'Ren Rhinx',
    niche: 'ABG Fitness',
    handle: '@rhinxrenx',
    igHandle: '@renxfit',
    color: '#833ab4',
    initials: 'RR',
    status: 'Active',
    pipelineStep: 'Filming',
    reelsInPipeline: 2,
    mrr: 3100,
    subscribers: 1320,
    manager: 'Kai T.',
    onboardingPhase: 6,
    contentReceived: 100,
    contractSignedAt: '2026-04-05T10:00:00Z',
    bio: 'Asian bad girl fitness aesthetic — streetwear meets gym. Targets 18-28 female audience.',
    onboardingSteps: [
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Face references uploaded (5+)', done: true, phase: 4 },
      { label: 'Soul ID trained (Higgsfield)', done: true, phase: 4 },
      { label: 'First AI batch generated', done: true, phase: 4 },
      { label: 'Batch reviewed & approved', done: true, phase: 4 },
      { label: 'Vault loaded (10+ PPV pieces)', done: true, phase: 4 },
      { label: 'First 2 weeks scheduled', done: true, phase: 5 },
      { label: 'Welcome sequence set up', done: true, phase: 5 },
      { label: 'Chatter briefed', done: true, phase: 5 },
      { label: 'Account launched', done: true, phase: 6 },
      { label: 'First PPV blast sent', done: false, phase: 6 },
      { label: 'Traffic campaigns running', done: false, phase: 6 },
      { label: 'Week 1 performance reviewed', done: false, phase: 7 },
      { label: 'Strategy call complete', done: false, phase: 7 },
    ] as OnboardingPhaseStep[],
  },
  {
    id: 'm3',
    name: 'Ella Mira',
    niche: 'Lifestyle GFE',
    handle: '@ellamira',
    igHandle: '@ella.mira',
    color: '#22c55e',
    initials: 'EM',
    status: 'Active',
    pipelineStep: 'Complete',
    reelsInPipeline: 5,
    mrr: 2800,
    subscribers: 3150,
    manager: 'Jordan M.',
    onboardingPhase: 7,
    contentReceived: 100,
    bio: 'Girlfriend experience lifestyle creator. Morning routines, cosy aesthetics, and intimate daily vlogs.',
    onboardingSteps: [
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Face references uploaded (5+)', done: true, phase: 4 },
      { label: 'Soul ID trained (Higgsfield)', done: true, phase: 4 },
      { label: 'First AI batch generated', done: true, phase: 4 },
      { label: 'Batch reviewed & approved', done: true, phase: 4 },
      { label: 'Vault loaded (10+ PPV pieces)', done: true, phase: 4 },
      { label: 'First 2 weeks scheduled', done: true, phase: 5 },
      { label: 'Welcome sequence set up', done: true, phase: 5 },
      { label: 'Chatter briefed', done: true, phase: 5 },
      { label: 'Account launched', done: true, phase: 6 },
      { label: 'First PPV blast sent', done: true, phase: 6 },
      { label: 'Traffic campaigns running', done: true, phase: 6 },
      { label: 'Week 1 performance reviewed', done: true, phase: 7 },
      { label: 'Strategy call complete', done: true, phase: 7 },
    ] as OnboardingPhaseStep[],
  },
  {
    id: 'm4',
    name: 'Sam Chase',
    niche: 'GFE',
    handle: '@samchase_of',
    igHandle: '@sam.chase.of',
    color: '#f59e0b',
    initials: 'SC',
    status: 'Paused',
    pipelineStep: 'Clips Received',
    reelsInPipeline: 1,
    mrr: 1900,
    subscribers: 540,
    manager: 'Kai T.',
    onboardingPhase: 4,
    contentReceived: 34,
    contractSignedAt: '2026-04-06T01:00:00Z',
    bio: 'Soft GFE creator with cute, approachable aesthetic. Currently paused — pending content review.',
    onboardingSteps: [
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Face references uploaded (5+)', done: true, phase: 4 },
      { label: 'Soul ID trained (Higgsfield)', done: false, phase: 4 },
      { label: 'First AI batch generated', done: false, phase: 4 },
      { label: 'Batch reviewed & approved', done: false, phase: 4 },
      { label: 'Vault loaded (10+ PPV pieces)', done: false, phase: 4 },
      { label: 'First 2 weeks scheduled', done: false, phase: 5 },
      { label: 'Welcome sequence set up', done: false, phase: 5 },
      { label: 'Chatter briefed', done: false, phase: 5 },
      { label: 'Account launched', done: false, phase: 6 },
      { label: 'First PPV blast sent', done: false, phase: 6 },
      { label: 'Traffic campaigns running', done: false, phase: 6 },
      { label: 'Week 1 performance reviewed', done: false, phase: 7 },
      { label: 'Strategy call complete', done: false, phase: 7 },
    ] as OnboardingPhaseStep[],
  },
];

export const KANBAN_COLUMNS = [
  { id: 1, label: 'Application' },
  { id: 2, label: 'Profile Setup' },
  { id: 3, label: 'Content Brief' },
  { id: 4, label: 'Training' },
  { id: 5, label: 'Active' },
];
