import type { EmployeePay, ModelEarnings } from './types';

export const TEAM_PAYROLL: EmployeePay[] = [
  {
    id: 'sofia',
    name: 'Sofia',
    role: 'Chatter',
    department: 'Sales',
    basePay: 550,
    deductions: 0,
    bonuses: 15,
    commission: 320,
    status: 'pending',
  },
  {
    id: 'kristine',
    name: 'Kristine',
    role: 'Chatter',
    department: 'Sales',
    basePay: 550,
    deductions: 10,
    bonuses: 0,
    commission: 280,
    status: 'pending',
  },
  {
    id: 'macy',
    name: 'Macy',
    role: 'Chatter',
    department: 'Sales',
    basePay: 550,
    deductions: 0,
    bonuses: 20,
    commission: 195,
    status: 'pending',
  },
  {
    id: 'yssa',
    name: 'Yssa',
    role: 'Social VA',
    department: 'Social Media',
    basePay: 550,
    deductions: 0,
    bonuses: 25,
    commission: 0,
    status: 'pending',
  },
  {
    id: 'mikeee',
    name: 'Mikeee',
    role: 'Social VA',
    department: 'Social Media',
    basePay: 550,
    deductions: 10,
    bonuses: 0,
    commission: 0,
    status: 'pending',
  },
  {
    id: 'aria',
    name: 'Aria',
    role: 'Manager',
    department: 'Management',
    basePay: 0,
    deductions: 0,
    bonuses: 0,
    commission: 0,
    status: 'processing',
  },
  {
    id: 'jack',
    name: 'Jack',
    role: 'Manager',
    department: 'Management',
    basePay: 0,
    deductions: 0,
    bonuses: 0,
    commission: 0,
    status: 'paid',
  },
];

export const MODEL_EARNINGS: ModelEarnings[] = [
  {
    id: 'tyler',
    name: 'Tyler Rex',
    initials: 'TR',
    gradient: 'linear-gradient(135deg, #ff0069, #833ab4)',
    revenue: 4800,
    margin: 62,
    trend: 'up',
    trendValue: '+12%',
  },
  {
    id: 'ren',
    name: 'Ren Rhinx',
    initials: 'RR',
    gradient: 'linear-gradient(135deg, #833ab4, #fd1d1d)',
    revenue: 3600,
    margin: 58,
    trend: 'up',
    trendValue: '+8%',
  },
  {
    id: 'ella',
    name: 'Ella Mira',
    initials: 'EM',
    gradient: 'linear-gradient(135deg, #f77737, #fcaf45)',
    revenue: 2900,
    margin: 55,
    trend: 'down',
    trendValue: '-3%',
  },
  {
    id: 'sam',
    name: 'Sam Chase',
    initials: 'SC',
    gradient: 'linear-gradient(135deg, #0ea5e9, #06b6d4)',
    revenue: 2100,
    margin: 60,
    trend: 'flat',
    trendValue: '0%',
  },
];
