import type { PipelineStep, ModelData, OnboardingPhaseStep } from './types';

export const PIPELINE_STEPS: PipelineStep[] = [
  'Draft', 'Sent', 'Filming', 'Clips Received', 'Editing', 'Complete',
];


export const MODELS: ModelData[] = [
  {
    id: 'm1',
    name: 'Tyler',
    niche: 'Gay Bear Fitness',
    handle: '@onlytylerrex',
    igHandle: '@tylerrex_fit',
    color: '#ff0069',
    initials: 'TY',
    status: 'Active',
    pipelineStep: 'Editing',
    reelsInPipeline: 3,
    mrr: 4200,
    subscribers: 1840,
    manager: 'Jordan M.',
    onboardingPhase: 7,
    contentReceived: 100,
    bio: 'Gay bear fitness creator focused on strength training, body positivity, and gym lifestyle content. High engagement from 25-40 male demographic.',
    onboardingSteps: [
      // Phases 1-6 all done
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Minimum 100 pieces submitted', done: true, phase: 4 },
      { label: 'Lighting/quality reviewed', done: true, phase: 4 },
      { label: 'Revisions complete', done: true, phase: 4 },
      { label: 'Vault stocked (10+ PPV pieces)', done: true, phase: 4 },
      { label: 'First 2 weeks scheduled', done: true, phase: 5 },
      { label: 'Welcome sequence set up', done: true, phase: 5 },
      { label: 'Chatter briefed', done: true, phase: 5 },
      { label: 'Account launched', done: true, phase: 6 },
      { label: 'First PPV blast sent', done: true, phase: 6 },
      { label: 'Traffic campaigns running', done: true, phase: 6 },
      // Phase 7 - current, some done
      { label: 'Week 1 performance reviewed', done: true, phase: 7 },
      { label: 'Strategy call complete', done: false, phase: 7 },
    ] as OnboardingPhaseStep[],
    reels: [
      { id: 'r1-1', title: 'Morning chest pump 🔥', step: 'Editing', gradient: 'linear-gradient(135deg, #ff0069 0%, #833ab4 100%)', createdAt: '2026-04-04', provider: 'Kling', jobStatus: 'Generating' },
      { id: 'r1-2', title: 'Bear mode bulk update', step: 'Clips Received', gradient: 'linear-gradient(135deg, #833ab4 0%, #06b6d4 100%)', createdAt: '2026-04-03' },
      { id: 'r1-3', title: 'Deadlift PR attempt', step: 'Complete', gradient: 'linear-gradient(135deg, #f59e0b 0%, #ff0069 100%)', createdAt: '2026-03-29', provider: 'Higgsfield', jobStatus: 'Done' },
      { id: 'r1-4', title: 'Post-gym shower routine', step: 'Draft', gradient: 'linear-gradient(135deg, #22c55e 0%, #06b6d4 100%)', createdAt: '2026-04-05' },
    ],
  },
  {
    id: 'm2',
    name: 'Ren',
    niche: 'ABG Fitness',
    handle: '@rhinxrenx',
    igHandle: '@renxfit',
    color: '#833ab4',
    initials: 'RN',
    status: 'Active',
    pipelineStep: 'Filming',
    reelsInPipeline: 2,
    mrr: 3100,
    subscribers: 1320,
    manager: 'Kai T.',
    onboardingPhase: 6,
    contentReceived: 100,
    contractSignedAt: '2026-04-05T10:00:00Z',
    bio: 'Asian bad girl fitness aesthetic - streetwear meets gym. Targets 18-28 female audience with fashion-forward workout content and lifestyle vlogs.',
    onboardingSteps: [
      // Phases 1-5 all done
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Minimum 100 pieces submitted', done: true, phase: 4 },
      { label: 'Lighting/quality reviewed', done: true, phase: 4 },
      { label: 'Revisions complete', done: true, phase: 4 },
      { label: 'Vault stocked (10+ PPV pieces)', done: true, phase: 4 },
      { label: 'First 2 weeks scheduled', done: true, phase: 5 },
      { label: 'Welcome sequence set up', done: true, phase: 5 },
      { label: 'Chatter briefed', done: true, phase: 5 },
      // Phase 6 - current, some done
      { label: 'Account launched', done: true, phase: 6 },
      { label: 'First PPV blast sent', done: false, phase: 6 },
      { label: 'Traffic campaigns running', done: false, phase: 6 },
      // Phase 7 - not started
      { label: 'Week 1 performance reviewed', done: false, phase: 7 },
      { label: 'Strategy call complete', done: false, phase: 7 },
    ] as OnboardingPhaseStep[],
    reels: [
      { id: 'r2-1', title: 'Streetwear gym fit check', step: 'Filming', gradient: 'linear-gradient(135deg, #833ab4 0%, #06b6d4 100%)', createdAt: '2026-04-05' },
      { id: 'r2-2', title: 'Glute day - ABG edition', step: 'Sent', gradient: 'linear-gradient(135deg, #ff0069 0%, #833ab4 100%)', createdAt: '2026-04-02' },
      { id: 'r2-3', title: 'Unboxing my new lulus', step: 'Complete', gradient: 'linear-gradient(135deg, #22c55e 0%, #06b6d4 100%)', createdAt: '2026-03-28', provider: 'Higgsfield', jobStatus: 'Done' },
    ],
  },
  {
    id: 'm3',
    name: 'Ella',
    niche: 'Lifestyle GFE',
    handle: '@ellamira',
    igHandle: '@ella.mira',
    color: '#22c55e',
    initials: 'EL',
    status: 'Active',
    pipelineStep: 'Complete',
    reelsInPipeline: 5,
    mrr: 6800,
    subscribers: 3150,
    manager: 'Jordan M.',
    onboardingPhase: 7,
    contentReceived: 100,
    bio: 'Girlfriend experience lifestyle creator. Morning routines, cosy aesthetics, and intimate daily vlogs. Highest MRR in the roster with strong retention metrics.',
    onboardingSteps: [
      // All phases done
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      { label: 'Minimum 100 pieces submitted', done: true, phase: 4 },
      { label: 'Lighting/quality reviewed', done: true, phase: 4 },
      { label: 'Revisions complete', done: true, phase: 4 },
      { label: 'Vault stocked (10+ PPV pieces)', done: true, phase: 4 },
      { label: 'First 2 weeks scheduled', done: true, phase: 5 },
      { label: 'Welcome sequence set up', done: true, phase: 5 },
      { label: 'Chatter briefed', done: true, phase: 5 },
      { label: 'Account launched', done: true, phase: 6 },
      { label: 'First PPV blast sent', done: true, phase: 6 },
      { label: 'Traffic campaigns running', done: true, phase: 6 },
      { label: 'Week 1 performance reviewed', done: true, phase: 7 },
      { label: 'Strategy call complete', done: true, phase: 7 },
    ] as OnboardingPhaseStep[],
    reels: [
      { id: 'r3-1', title: 'Morning coffee with me ☕', step: 'Complete', gradient: 'linear-gradient(135deg, #22c55e 0%, #06b6d4 100%)', createdAt: '2026-04-04', provider: 'Higgsfield', jobStatus: 'Done' },
      { id: 'r3-2', title: 'Skincare night routine', step: 'Complete', gradient: 'linear-gradient(135deg, #f59e0b 0%, #22c55e 100%)', createdAt: '2026-04-03', provider: 'Higgsfield', jobStatus: 'Done' },
      { id: 'r3-3', title: 'Cosy Sunday vlog', step: 'Editing', gradient: 'linear-gradient(135deg, #06b6d4 0%, #833ab4 100%)', createdAt: '2026-04-05', provider: 'Kling', jobStatus: 'Generating' },
      { id: 'r3-4', title: 'Cooking for you tonight', step: 'Filming', gradient: 'linear-gradient(135deg, #ff0069 0%, #f59e0b 100%)', createdAt: '2026-04-06' },
      { id: 'r3-5', title: 'GRWM date night look', step: 'Draft', gradient: 'linear-gradient(135deg, #833ab4 0%, #22c55e 100%)', createdAt: '2026-04-06' },
    ],
  },
  {
    id: 'm4',
    name: 'Amam',
    niche: 'GFE',
    handle: '@abg.ricebunny',
    igHandle: '@ricebunny.of',
    color: '#f59e0b',
    initials: 'AM',
    status: 'Paused',
    pipelineStep: 'Clips Received',
    reelsInPipeline: 1,
    mrr: 1200,
    subscribers: 540,
    manager: 'Kai T.',
    onboardingPhase: 4,
    contentReceived: 34,
    contractSignedAt: '2026-04-06T01:00:00Z',
    bio: 'Soft GFE creator with cute, approachable aesthetic. Currently paused - pending content review and re-brief before relaunching campaign.',
    onboardingSteps: [
      // Phases 1-3 all done
      { label: 'Application reviewed', done: true, phase: 1 },
      { label: 'Video call completed', done: true, phase: 1 },
      { label: 'Content verified', done: true, phase: 1 },
      { label: 'Contract signed', done: true, phase: 2 },
      { label: 'ID verified', done: true, phase: 2 },
      { label: 'Age verification processed', done: true, phase: 2 },
      { label: 'OF profile optimised', done: true, phase: 3 },
      { label: 'Sub price set', done: true, phase: 3 },
      { label: 'Free trial link created', done: true, phase: 3 },
      { label: 'Social profiles linked', done: true, phase: 3 },
      // Phase 4 - current, some done
      { label: 'Face references uploaded (5+)', done: true, phase: 4 },
      { label: 'Soul ID trained (Higgsfield)', done: false, phase: 4 },
      { label: 'First AI batch generated', done: false, phase: 4 },
      { label: 'Batch reviewed & approved', done: false, phase: 4 },
      { label: 'Vault loaded (10+ PPV pieces)', done: false, phase: 4 },
      // Phases 5-7 - not started
      { label: 'First 2 weeks scheduled', done: false, phase: 5 },
      { label: 'Welcome sequence set up', done: false, phase: 5 },
      { label: 'Chatter briefed', done: false, phase: 5 },
      { label: 'Account launched', done: false, phase: 6 },
      { label: 'First PPV blast sent', done: false, phase: 6 },
      { label: 'Traffic campaigns running', done: false, phase: 6 },
      { label: 'Week 1 performance reviewed', done: false, phase: 7 },
      { label: 'Strategy call complete', done: false, phase: 7 },
    ] as OnboardingPhaseStep[],
    reels: [
      { id: 'r4-1', title: 'Bunny aesthetic - intro', step: 'Clips Received', gradient: 'linear-gradient(135deg, #f59e0b 0%, #ff0069 100%)', createdAt: '2026-04-01' },
    ],
  },
];

export const THUMB_GRADIENTS = [
  'linear-gradient(135deg, #ff0069 0%, #833ab4 100%)',
  'linear-gradient(135deg, #833ab4 0%, #06b6d4 100%)',
  'linear-gradient(135deg, #f59e0b 0%, #ff0069 100%)',
  'linear-gradient(135deg, #22c55e 0%, #06b6d4 100%)',
];
