/**
 * Portfolio Client Data - Template
 *
 * INSTRUCTIONS:
 * 1. Copy this file and rename it to the client slug (e.g., uber-crypt.ts)
 * 2. Replace all [PLACEHOLDERS] with actual data
 * 3. Remove optional fields if not applicable (marketAnalysis, aiAgents, results, testimonial)
 * 4. Update export name to match client slug
 */

import { PortfolioClient } from '../../types';

/**
 * Example portfolio client.
 * Duplicate this file, rename it to the client slug, and replace
 * the sample values with real data before exporting from index.ts.
 */
export const CLIENT_TEMPLATE: PortfolioClient = {
  // Basic Info
  id: 'client-template',
  name: 'Client Template',
  industry: 'saas',
  tagline: 'Reference entry for new portfolio clients',
  description:
    'Use this file as a reference when defining new portfolio clients. Replace the values below with project-specific data.',

  // URLs
  liveUrl: 'https://example.com',
  githubUrl: undefined,
  caseStudyUrl: undefined,

  // Project Details
  projectType: 'Web App',
  status: 'In Development',
  launchDate: '2025-01-01',

  // Timeline
  timeline: {
    startDate: '2024-12-01',
    endDate: '2025-01-15',
    durationDays: 45,
    phases: [
      {
        name: 'Day 1',
        description: 'Kickoff + solution outline',
        completedDate: '2024-12-01',
      },
      {
        name: 'Design',
        description: 'Wireframes + UI system',
        completedDate: '2024-12-07',
      },
      {
        name: 'Build',
        description: 'Feature implementation + QA',
        completedDate: '2025-01-10',
      },
    ],
  },

  // Pricing
  pricing: {
    marketValue: 32000,
    sisoPrice: 18000,
    currency: 'GBP',
    priceRange: '£15,000 - £20,000',
    paymentStructure: '50% Day 1, 50% on completion',
    savings: 44,
  },

  // Features
  features: {
    key: ['Self-serve onboarding', 'Modular CMS blocks', 'Post-login dashboard'],
    technical: ['Next.js streaming routes', 'Edge caching', 'AI-powered insights'],
    integrations: ['Stripe', 'HubSpot'],
  },

  // Tech Stack
  techStack: {
    frontend: ['Next.js', 'Tailwind CSS'],
    backend: ['Node.js', 'tRPC'],
    database: ['PostgreSQL'],
    hosting: ['Vercel'],
    tools: ['Figma', 'Linear'],
  },

  // Market Analysis (OPTIONAL)
  marketAnalysis: {
    competitorsSurveyed: ['Competitor A', 'Competitor B'],
    uniqueSellingPoints: ['Faster launch windows', 'Integrated AI copilots'],
    targetAudience: 'Growth-stage SaaS teams',
    marketPosition: 'Premium GTM experiences at day-one cost',
  },

  // AI Agents (OPTIONAL)
  aiAgents: {
    agentsUsed: ['Analyst', 'PM', 'Dev'],
    workPerformed: ['Competitor tear-downs', 'Prompt scaffolding'],
    automationHighlights: ['Autogenerated onboarding copy', 'Test data hydrators'],
  },

  // Results (OPTIONAL)
  results: {
    deliverySpeed: '45 days from brief to live beta',
    performanceMetrics: {
      pageLoadTime: '1.3s',
      lighthouseScore: 93,
      uptime: '99.9%',
    },
    businessImpact: 'Unlocked a net-new self-serve channel projected to add £1.2M ARR.',
    clientSatisfaction: 5,
  },

  // Testimonial (OPTIONAL)
  testimonial: {
    quote: 'SISO delivered a polished experience faster than our internal teams could scope it.',
    author: 'Jordan Riley',
    title: 'COO, Example SaaS',
    photo: '/portfolio/client-template/testimonial.jpg',
  },

  // Media
  media: {
    logo: '/portfolio/[client-slug]/logo.png',
    screenshots: {
      desktop: [
        '/portfolio/[client-slug]/desktop/hero.png',
        '/portfolio/[client-slug]/desktop/page-1.png',
        // Add more
      ],
      mobile: [
        '/portfolio/[client-slug]/mobile/home.png',
        '/portfolio/[client-slug]/mobile/page-1.png',
        // Add more
      ],
      features: [
        '/portfolio/[client-slug]/features/feature-1.png',
        // Add more
      ],
    },
    videos: [], // Optional
  },

  // Metadata
  metadata: {
    featured: false, // true if should appear in featured section
    showInPortfolio: true,
    seoTitle: '[Client Name] - [Project Type] | SISO Portfolio',
    seoDescription: '[SEO-optimized description including key features and tech]',
    tags: ['[tag1]', '[tag2]', '[tag3]'], // Relevant keywords
  },
};
