import type { Channel, Message, Announcement } from './types';

export const CHANNELS: Channel[] = [
  {
    id: 'ch-general',
    name: 'general',
    group: 'Chatters',
    unread: 2,
    members: 12,
    lastMessage: {
      sender: 'Sofia',
      preview: 'The new content brief template is ready for review',
      timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'ch-models',
    name: 'models',
    group: 'Managers',
    unread: 0,
    members: 5,
    lastMessage: {
      sender: 'Alex',
      preview: 'Reminder: Update all model availability by EOD',
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'ch-chatters',
    name: 'chatters',
    group: 'Chatters',
    unread: 5,
    members: 14,
    lastMessage: {
      sender: 'Kristine',
      preview: 'Just posted the schedule for next week — check the pinned message',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'ch-managers',
    name: 'managers',
    group: 'Managers',
    unread: 0,
    members: 4,
    lastMessage: {
      sender: 'Alex',
      preview: 'Q2 targets are updated in the shared drive',
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'ch-urgent',
    name: 'urgent',
    group: 'Departments',
    unread: 1,
    members: 24,
    lastMessage: {
      sender: 'Jordan',
      preview: '[@channel] Platform maintenance window at 2am — expect downtime',
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
  },
];

export const MESSAGES: Record<string, Message[]> = {
  'ch-general': [
    {
      id: 'msg-g1',
      channelId: 'ch-general',
      sender: 'Sofia',
      senderRole: 'Chatter',
      senderInitials: 'S',
      senderColor: '#ff0069',
      content: 'Hey team! Just finished the new content brief template — it should save us a lot of time going forward.',
      timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-g2',
      channelId: 'ch-general',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: 'Looks great Sofia! I especially like the structure for the hook section.',
      timestamp: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-g3',
      channelId: 'ch-general',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'Perfect timing. Rolling this out to all models this week.',
      timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-g4',
      channelId: 'ch-general',
      sender: 'Kristine',
      senderRole: 'Chatter',
      senderInitials: 'K',
      senderColor: '#f77737',
      content: 'Can we add a field for target audience demographics?',
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-g5',
      channelId: 'ch-general',
      sender: 'Sofia',
      senderRole: 'Chatter',
      senderInitials: 'S',
      senderColor: '#ff0069',
      content: 'Already added it! Also included a competitor reference field.',
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-g6',
      channelId: 'ch-general',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'The new content brief template is ready for review',
      timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      isMe: false,
    },
  ],
  'ch-models': [
    {
      id: 'msg-m1',
      channelId: 'ch-models',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'Reminder: update all model availability by EOD today.',
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-m2',
      channelId: 'ch-models',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: "Done for Tyler and Ren. Waiting on Ella's response.",
      timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-m3',
      channelId: 'ch-models',
      sender: 'Sofia',
      senderRole: 'Chatter',
      senderInitials: 'S',
      senderColor: '#ff0069',
      content: "Sam Chase updated theirs yesterday — all clear for next week.",
      timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-m4',
      channelId: 'ch-models',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'Great. Jordan follow up with Ella please.',
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-m5',
      channelId: 'ch-models',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: "On it. Will ping her now.",
      timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-m6',
      channelId: 'ch-models',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: "Reminder: Update all model availability by EOD",
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      isMe: false,
    },
  ],
  'ch-chatters': [
    {
      id: 'msg-c1',
      channelId: 'ch-chatters',
      sender: 'Kristine',
      senderRole: 'Chatter',
      senderInitials: 'K',
      senderColor: '#f77737',
      content: 'Schedule for next week is out — check the pinned message!',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-c2',
      channelId: 'ch-chatters',
      sender: 'Sofia',
      senderRole: 'Chatter',
      senderInitials: 'S',
      senderColor: '#ff0069',
      content: "Got it, thanks! I'm on the 9am-5pm block right?",
      timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-c3',
      channelId: 'ch-chatters',
      sender: 'Kristine',
      senderRole: 'Chatter',
      senderInitials: 'K',
      senderColor: '#f77737',
      content: 'Yes, same as usual. Let me know if you need a swap.',
      timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-c4',
      channelId: 'ch-chatters',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: "I can cover the night shift Mon-Wed if anyone needs it.",
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-c5',
      channelId: 'ch-chatters',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'Thanks Jordan. Putting you down for Mon-Wed nights.',
      timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-c6',
      channelId: 'ch-chatters',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: "Just posted the schedule for next week — check the pinned message",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
  ],
  'ch-managers': [
    {
      id: 'msg-mg1',
      channelId: 'ch-managers',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'Q2 targets are updated in the shared drive. Review before Friday.',
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-mg2',
      channelId: 'ch-managers',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: 'Revenue target is up 18% from Q1. All hands Monday to discuss.',
      timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-mg3',
      channelId: 'ch-managers',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: "Q2 targets are updated in the shared drive",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      isMe: false,
    },
  ],
  'ch-urgent': [
    {
      id: 'msg-u1',
      channelId: 'ch-urgent',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: '[@channel] Platform maintenance window at 2am UTC — expect ~30min downtime.',
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-u2',
      channelId: 'ch-urgent',
      sender: 'Sofia',
      senderRole: 'Chatter',
      senderInitials: 'S',
      senderColor: '#ff0069',
      content: "Will this affect scheduled posts?",
      timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-u3',
      channelId: 'ch-urgent',
      sender: 'Jordan',
      senderRole: 'VA',
      senderInitials: 'J',
      senderColor: '#833ab4',
      content: 'Yes — all scheduled posts in that window will retry automatically after.',
      timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      isMe: false,
    },
    {
      id: 'msg-u4',
      channelId: 'ch-urgent',
      sender: 'Alex',
      senderRole: 'Manager',
      senderInitials: 'A',
      senderColor: '#4ade80',
      content: "[@channel] Platform maintenance window at 2am — expect downtime",
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isMe: false,
    },
  ],
};

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Q2 Revenue Target: $180K',
    body: 'We are targeting $180K in Q2 revenue — an 18% increase over Q1. All teams should align on growth initiatives by end of month.',
    author: 'Alex',
    authorRole: 'Owner',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    pinned: true,
    priority: 'high',
  },
  {
    id: 'ann-2',
    title: 'New Model Onboarding Process',
    body: 'Starting April 15, all new models go through the updated onboarding flow: Application → Profile Setup → Content Brief → Training → Active.',
    author: 'Alex',
    authorRole: 'Owner',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    pinned: true,
    priority: 'normal',
  },
  {
    id: 'ann-3',
    title: 'Platform Maintenance: April 14, 2am UTC',
    body: 'Scheduled 30-minute maintenance window on April 14. All scheduled posts will retry automatically. No action needed from chatters.',
    author: 'Jordan',
    authorRole: 'VA',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    pinned: false,
    priority: 'high',
  },
  {
    id: 'ann-4',
    title: 'Welcome Sam Chase to the Roster',
    body: 'Sam Chase has joined as our newest model. Everyone give a warm welcome — they are already active in #general.',
    author: 'Alex',
    authorRole: 'Owner',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    pinned: false,
    priority: 'normal',
  },
];

export const CHANNEL_GROUPS = ['Chatters', 'Managers', 'Departments'];

export const ONLINE_COUNT = 9;
