import type { Post } from './types';
import { CREATORS, GRADIENTS } from './data';

export const POSTS: Post[] = [
  {
    id: '1',
    type: 'Reel',
    niche: 'fitness',
    creator: CREATORS[0],
    gradient: GRADIENTS.pink,
    caption: 'Monday grind starts early. No excuses, just results. 5am club is real.',
    hashtags: ['#gymmotivation', '#gaybear', '#fitness'],
    likes: 8412, comments: 234, saves: 180, views: 89400,
    postedAt: '2h ago',
    isVideo: true,
    approved: true,
  },
  {
    id: '2',
    type: 'Post',
    niche: 'lifestyle',
    creator: CREATORS[2],
    gradient: GRADIENTS.purple,
    caption: 'Vibes only. That aesthetic everyone keeps trying to copy.',
    hashtags: ['#lifestyle', '#aesthetic'],
    likes: 6200, comments: 89, saves: 214, views: 67200,
    postedAt: '4h ago',
    isVideo: false,
    approved: true,
  },
  {
    id: '3',
    type: 'Carousel',
    niche: 'fashion',
    creator: CREATORS[1],
    gradient: GRADIENTS.amber,
    caption: 'OOTD but make it intentional. Every detail matters.',
    hashtags: ['#ootd', '#fashion', '#style'],
    likes: 4120, comments: 56, saves: 98, views: 34100,
    postedAt: '6h ago',
    isVideo: false,
  },
  {
    id: '4',
    type: 'Reel',
    niche: 'fitness',
    creator: CREATORS[3],
    gradient: GRADIENTS.green,
    caption: 'Transformation Tuesday. 12 weeks in. Same mirror, different energy.',
    hashtags: ['#transformation', '#fitness', '#progress'],
    likes: 7100, comments: 198, saves: 241, views: 76300,
    postedAt: '8h ago',
    isVideo: true,
    approved: true,
  },
  {
    id: '5',
    type: 'Post',
    niche: 'fitness',
    creator: CREATORS[0],
    gradient: GRADIENTS.indigo,
    caption: 'Post-workout glow. Consistency is the only hack you need.',
    hashtags: ['#postworkout', '#gymlife'],
    likes: 5500, comments: 112, saves: 132, views: 55000,
    postedAt: '12h ago',
    isVideo: false,
  },
  {
    id: '6',
    type: 'Reel',
    niche: 'fitness',
    creator: CREATORS[2],
    gradient: GRADIENTS.teal,
    caption: 'Pull-up progression: Week 1 to Week 12. No shortcuts.',
    hashtags: ['#calisthenics', '#progress', '#pullup'],
    likes: 12300, comments: 312, saves: 480, views: 145000,
    postedAt: '1d ago',
    isVideo: true,
    approved: true,
  },
  {
    id: '7',
    type: 'Carousel',
    niche: 'wellness',
    creator: CREATORS[1],
    gradient: GRADIENTS.amber,
    caption: '5 ways to stay consistent with your fitness goals.',
    hashtags: ['#fitnessgoals', '#tips', '#consistency'],
    likes: 3870, comments: 67, saves: 312, views: 28900,
    postedAt: '1d ago',
    isVideo: false,
    saved: true,
  },
  {
    id: '8',
    type: 'Reel',
    niche: 'lifestyle',
    creator: CREATORS[3],
    gradient: GRADIENTS.green,
    caption: 'Golden hour at the rooftop. When the city lights up.',
    hashtags: ['#goldenhour', '#lifestyle', '#rooftop'],
    likes: 9800, comments: 145, saves: 203, views: 91200,
    postedAt: '2d ago',
    isVideo: true,
    saved: true,
  },
  {
    id: '9',
    type: 'Post',
    niche: 'wellness',
    creator: CREATORS[2],
    gradient: GRADIENTS.purple,
    caption: 'Rest day = recovery day. This is where the growth actually happens.',
    hashtags: ['#restday', '#recovery', '#mobility'],
    likes: 4200, comments: 78, saves: 156, views: 38500,
    postedAt: '2d ago',
    isVideo: false,
  },
  {
    id: '10',
    type: 'Carousel',
    niche: 'fashion',
    creator: CREATORS[0],
    gradient: GRADIENTS.pink,
    caption: 'What I eat in a day. Full transparency, no shortcuts.',
    hashtags: ['#nutrition', '#mealprep', '#bodybuilding'],
    likes: 6800, comments: 189, saves: 427, views: 72000,
    postedAt: '3d ago',
    isVideo: false,
    saved: true,
  },
];
