import type { Applicant } from "./types";

export const ACCENT_GRADIENT = "linear-gradient(135deg, #ff0069, #833ab4)";

export const ALL_APPLICANTS: Applicant[] = [
  {
    id: "1",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    telegram: "@mariasantos",
    country: "Colombia",
    dept: "Sales",
    role: "Chatter",
    applied: "2026-04-10",
    appliedDays: "2 hours ago",
    status: "New",
    avatar: "MS",
    standout: "Native Spanish, fluent English, 2 years OFM experience",
    details: {
      platforms: ["OnlyFans", "Fansly"],
      contentTypes: ["Conversational", "PPV Sales"],
      typingSpeed: "Fast (50–80 wpm)",
      englishLevel: 8,
      hoursPerDay: "4–6 hours",
      shiftPref: "Evening",
    },
  },
  {
    id: "2",
    name: "Taylor Kim",
    email: "taylor.kim@example.com",
    telegram: "@taylorkim",
    country: "South Korea",
    dept: "Sales",
    role: "Chatter",
    applied: "2026-04-09",
    appliedDays: "1 day ago",
    status: "Screening",
    avatar: "TK",
    standout: "90 WPM typing — fastest applicant this month, 3.5 years exp",
    details: {
      platforms: ["OnlyFans"],
      contentTypes: ["Conversational", "Sexting"],
      typingSpeed: "Very Fast (80+ wpm)",
      englishLevel: 9,
      hoursPerDay: "6–8 hours",
      shiftPref: "Flexible",
    },
  },
  {
    id: "3",
    name: "Jamie Chen",
    email: "jamie.chen@example.com",
    telegram: "@jamiechen",
    country: "Australia",
    dept: "Marketing",
    role: "Social VA",
    applied: "2026-04-08",
    appliedDays: "2 days ago",
    status: "Interview",
    avatar: "JC",
    standout: "Grew a personal IG from 0 to 80K followers solo, managed 6 brand accounts",
    interviewDate: "2026-04-14",
    details: {
      software: ["Canva", "CapCut", "Premiere Pro"],
      contentTypes: ["Reels", "Posts", "Stories", "TikToks"],
      qualityRating: 4,
      speedRating: 5,
      creativityRating: 4,
      hoursPerWeek: "30–40",
    },
  },
  {
    id: "4",
    name: "Alex Rivera",
    email: "alex.rivera@example.com",
    telegram: "@alexrivera",
    country: "Philippines",
    dept: "Marketing",
    role: "Social VA",
    applied: "2026-04-07",
    appliedDays: "3 days ago",
    status: "Trial",
    avatar: "AR",
    standout: "Edited 200+ reels for a 500K follower account, 3 years experience",
    details: {
      software: ["Premiere Pro", "DaVinci Resolve", "Canva"],
      contentTypes: ["Reels", "TikToks", "Stories"],
      qualityRating: 5,
      speedRating: 4,
      creativityRating: 5,
      hoursPerWeek: "20–30",
      portfolio: "https://alexrivera.design",
    },
  },
  {
    id: "5",
    name: "Sam Patel",
    email: "sam.patel@example.com",
    telegram: "@sampatel",
    country: "India",
    dept: "Marketing",
    role: "Social VA",
    applied: "2026-04-05",
    appliedDays: "5 days ago",
    status: "Hired",
    avatar: "SP",
    standout: "Viral reel hit 2.1M views, After Effects expert, 5 years experience",
    details: {
      software: ["Canva", "After Effects"],
      contentTypes: ["Posts", "Stories", "PPV"],
      qualityRating: 4,
      speedRating: 4,
      creativityRating: 5,
      hoursPerWeek: "20–30",
      portfolio: "https://sampatel.myportfolio.com",
    },
  },
  {
    id: "6",
    name: "Casey Nguyen",
    email: "casey.nguyen@example.com",
    telegram: "@casenguyen",
    country: "Vietnam",
    dept: "Sales",
    role: "Chatter",
    applied: "2026-04-04",
    appliedDays: "6 days ago",
    status: "Screening",
    avatar: "CN",
    standout: "Multi-platform expert, Fansly + LoyalFans + OnlyFans, fast responder",
    details: {
      platforms: ["Fansly", "LoyalFans", "OnlyFans"],
      contentTypes: ["Conversational", "Sexting", "PPV Sales", "Custom Content"],
      typingSpeed: "Fast (50–80 wpm)",
      englishLevel: 7,
      hoursPerDay: "4–6 hours",
      shiftPref: "Evening",
    },
  },
  {
    id: "7",
    name: "Jordan Lee",
    email: "jordan.lee@example.com",
    telegram: "@jordanlee",
    country: "United States",
    dept: "Sales",
    role: "Chatter",
    applied: "2026-04-03",
    appliedDays: "7 days ago",
    status: "Rejected",
    avatar: "JL",
    standout: "Slow response times and availability concerns flagged by reviewer",
    details: {
      platforms: ["OnlyFans"],
      contentTypes: ["Conversational"],
      typingSpeed: "Average (30–50 wpm)",
      englishLevel: 6,
      hoursPerDay: "1–2 hours",
      shiftPref: "Morning",
    },
  },
  {
    id: "8",
    name: "Riley Morgan",
    email: "riley.morgan@example.com",
    telegram: "@rileymorgan",
    country: "United Kingdom",
    dept: "Marketing",
    role: "Social VA",
    applied: "2026-04-02",
    appliedDays: "8 days ago",
    status: "Interview",
    avatar: "RM",
    standout: "Final Cut Pro + DaVinci Resolve, YouTube Shorts specialist",
    interviewDate: "2026-04-13",
    details: {
      software: ["Final Cut Pro", "DaVinci Resolve"],
      contentTypes: ["YouTube Shorts", "Reels", "TikToks"],
      qualityRating: 5,
      speedRating: 3,
      creativityRating: 5,
      hoursPerWeek: "10–20",
    },
  },
  {
    id: "9",
    name: "Dana Cruz",
    email: "dana.cruz@example.com",
    telegram: "@danacruz",
    country: "Philippines",
    dept: "Sales",
    role: "Chatter",
    applied: "2026-04-01",
    appliedDays: "9 days ago",
    status: "Hired",
    avatar: "DC",
    standout: "Top 5% performer at previous agency, 4.8-star rated, $18K MRR generated",
    details: {
      platforms: ["Fansly", "OnlyFans"],
      contentTypes: ["Conversational", "PPV Sales"],
      typingSpeed: "Fast (50–80 wpm)",
      englishLevel: 8,
      hoursPerDay: "6–8 hours",
      shiftPref: "Flexible",
    },
  },
  {
    id: "10",
    name: "Chris Park",
    email: "chris.park@example.com",
    telegram: "@chrispark",
    country: "Canada",
    dept: "Marketing",
    role: "Manager",
    applied: "2026-04-09",
    appliedDays: "1 day ago",
    status: "New",
    avatar: "CP",
    standout: "5 years managing OFM agencies, P&L ownership, fluent bilingual",
    details: {
      software: ["Notion", "Slack", "Google Workspace"],
      hoursPerWeek: "40+",
      englishLevel: 10,
    },
  },
];

export const STATUS_CONFIG: Record<
  Applicant["status"],
  { color: string; bg: string; border: string }
> = {
  New: { color: "#ff0069", bg: "rgba(255,0,105,0.08)", border: "rgba(255,0,105,0.25)" },
  Screening: { color: "#3b82f6", bg: "rgba(59,130,246,0.08)", border: "rgba(59,130,246,0.25)" },
  Interview: { color: "#f59e0b", bg: "rgba(245,158,11,0.08)", border: "rgba(245,158,11,0.25)" },
  Trial: { color: "#8b5cf6", bg: "rgba(139,92,246,0.08)", border: "rgba(139,92,246,0.25)" },
  Hired: { color: "#22c55e", bg: "rgba(34,197,94,0.08)", border: "rgba(34,197,94,0.25)" },
  Rejected: { color: "#9ca3af", bg: "rgba(156,163,175,0.08)", border: "rgba(156,163,175,0.25)" },
};

export const PIPELINE_STAGES = [
  { id: "Applied", label: "Applied", color: "#9ca3af" },
  { id: "Screen", label: "Screen", color: "#3b82f6" },
  { id: "Interview", label: "Interview", color: "#f59e0b" },
  { id: "Trial", label: "Trial", color: "#8b5cf6" },
  { id: "Hired", label: "Hired", color: "#22c55e" },
];

export const DEPT_FILTERS = ["All", "Chatters", "Social VAs", "Managers"] as const;

export const STATUS_FILTERS = ["All", "New", "Screening", "Interview", "Trial", "Hired", "Rejected"] as const;
